#
# build_gg_list.R
#
# This script builds a mothur-compatible list file from the OTU-map data that
# is generated by greengenes and the de facto reference in QIIME. It assumes
# that gg_13_5_otus.tar.gz has been downloaded, uncompressed and is located
# in the data/references folder.
#
# Idea: The first column of these files is pretty meaningless. What we want is
# the sequence name in the second column and the names that follow it. This is
# roughly equivalent to that of the mothur-based  names file. The primary
# difference is that they cluster to 99% and then to 97% so the 97% mapping
#file does not have all of the sequence names that are in the 99% file.


# parse out the name of the reference sequence and all of the sequences that
# it maps to
get_otu_maps <- function(number, path="data/references/gg_13_5_otus/otus/"){
	file_path <- paste0(path, number, "_otu_map.txt")
	otu_map_text <- scan(file_path, what="", sep="\n", quiet=TRUE)

	names(otu_map_text) <- gsub("^\\d*\\t(\\d*).*", "\\1", otu_map_text)
	otu_map_text <- gsub("^\\d*\t", "", otu_map_text)

	return(otu_map_text)
}

ninety_nine <- get_otu_maps(99)
ninety_seven <- get_otu_maps(97)


# for the 99% mapping file we want to separate each sequence name with a comma
collapse_otus <- function(otu_numbers){
	gsub("\t", ",", otu_numbers)
}
ninety_nine_commas <- sapply(ninety_nine, collapse_otus)


# we need to map the 99% data into the 97% data OTUs
expand_otus <- function(otu_number_string){
	split_string <- unlist(strsplit(otu_number_string, "\t"))
	paste(ninety_nine_commas[split_string], collapse=",")
}
ninety_seven_list <- sapply(ninety_seven, expand_otus)

# create the list file format and output to the data/gg_13_5 folder
list_data <- paste(c(97, length(ninety_seven_list), ninety_seven_list), collapse="\t")
write(list_data, "data/gg_13_5/gg_13_5_otus.ref.list")
